development:
  adapter: postgresql
  encoding: unicode
  database: nerd_restaurant_dev
  username: vagrant
  password: abcd1234
  pool: 5

assets:
  adapter: postgresql
  encoding: unicode
  database: nerd_restaurant_dev
  username: vagrant
  password: abcd1234
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: nerd_restaurant_test
  username: vagrant
  password: abcd1234
  pool: 5
  min_messages: WARNING

production:
  adapter: postgresql
  encoding: unicode
  database: nerd_restaurant_prod
  username: vagrant
  password: abcd1234
  pool: 5
